<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <!-- flipped = -1, normal = 1 for flip_x and isrear -->
    <xacro:macro name="db_module_corner" params="prefix parent flip_x:=1 isrear:=1">
        <joint name="${prefix}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${prefix}"/>
            <origin xyz="${isrear*(diff_bar_length/2 + 0.056/2)*cos(pi/6)} ${(diff_bar_length/2 + 0.056/2)*sin(pi/6)} 0" rpy="0 0 ${isrear*pi/6}" />
        </joint>

        <!-- TODO: Fix xyz -->
        <joint name="${prefix}_bar_smount_joint" type="fixed">
            <parent link="${prefix}"/>
            <child link="${prefix}_smount"/>
            <origin xyz="${isrear*diff_bar_length/2} ${0.05} ${(0.0425 + 0.02975)*flip_x}" rpy="${pi/2} 0 ${isrear*(pi/-6)}" />
        </joint>

        <!-- This is the steering joint, TODO: add limits -->
        <joint name="${prefix}_smount_fork_joint" type="continuous">
            <parent link="${prefix}_smount"/>
            <child link="${prefix}_wheel_fork"/>
            <origin xyz="0 0 ${-0.213/2 - 0.03/2}" rpy="0 0 0" />
            <axis xyz="0 0 1"/>
        </joint>

        <!-- This is the actual wheel -->
        <joint name="${prefix}_fork_tyre_joint" type="continuous">
            <parent link="${prefix}_wheel_fork"/>
            <child link="${prefix}_tyre"/>
            <origin xyz="0 0 ${-0.05}" rpy="${-pi/2} 0 0" />
            <axis xyz="0 0 1"/>
        </joint>


        <!-- ALL LINKS BELOW THIS LINE -->

        <link name="${prefix}">
            <visual>
                <geometry>
                    <box size="${diff_bar_length} ${diff_bar_bearing_seat_width} ${diff_bar_bearing_seat_width}"/>
                </geometry>
                <material name="orange"/>
            </visual>
        </link>

        <!-- Steering mount -->
        <link name="${prefix}_smount">
            <visual>
                <geometry>
                    <cylinder radius="${0.0425}" length="0.03"/>
                </geometry>
                <material name="orange"/>
            </visual>
        </link>

        <!-- The actual steering joint -->
        <link name="${prefix}_wheel_fork">
            <visual>
                <geometry>
                    <box size="0.066 0.170 0.213"/>
                </geometry>
                <material name="blue"/>
                
            </visual>
        </link>

        <!-- Wheel -->
        <link name="${prefix}_tyre">
            <visual>
                <geometry>
                    <cylinder radius="${0.125}" length="0.150"/>
                </geometry>
                <material name="black"/>
            </visual>
        </link>
    </xacro:macro>
</robot>