<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:include filename="db_helpers.xacro" />
    <xacro:include filename="ros2_control.xacro"/>

    <xacro:property name="diff_bar_bearing_seat_width" value="0.04"/>
    <xacro:property name="diff_bar_length" value="0.600"/>

    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.3"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>

    <!-- LEFT SIDE STUFF -->
    <!-- TODO: Fix effort and velocity limits. Current values are arbitrary. -->
    <joint name="ldb_pivot_joint" type="revolute">
        <parent link="chassis"/>
        <child link="ldb_pivot"/>
        <origin xyz="0 ${chassis_width/2 + 0.014 + diff_bar_bearing_seat_width} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
        <limit lower="${-pi/6}" upper="${pi/6}" effort="80.0" velocity="10.0"/>
    </joint>

    <link name="ldb_pivot">
        <visual>
            <geometry>
                <cylinder radius="${0.056/2}" length="${diff_bar_bearing_seat_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>


    <xacro:db_module_corner prefix="db_fl" isrear="1" parent="ldb_pivot"/>
    <xacro:db_module_corner prefix="db_bl" isrear="-1" parent="ldb_pivot"/>
    
    <!-- RIGHT SIDE STUFF -->
    <!-- TODO: Fix effort and velocity limits -->
    <joint name="rdb_pivot_joint" type="continuous">
        <parent link="chassis"/>
        <child link="rdb_pivot"/>
        <origin xyz="0 -${chassis_width/2 + 0.014 + diff_bar_bearing_seat_width} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
        <limit lower="${-pi/6}" upper="${pi/6}" effort="0.0" velocity="0.0"/>
        <!-- TODO: <mimic joint="ldb_pivot_joint" multiplier="-1"/> -->
    </joint>

    <link name="rdb_pivot">
        <visual>
            <geometry>
                <cylinder radius="${0.056/2}" length="${diff_bar_bearing_seat_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <xacro:db_module_corner prefix="db_fr" isrear="1" flip_x="-1" parent="rdb_pivot"/>
    <xacro:db_module_corner prefix="db_br" isrear="-1" flip_x="-1" parent="rdb_pivot"/>

</robot>
