<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <!-- flipped = -1, normal = 1 for flip_x and isrear -->
	<xacro:macro name="db_module_corner" params="prefix parent flip_x:=1 isrear:=1">
	<!-- This is the pivot point -->
        <joint name="${prefix}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${prefix}"/>
            <origin xyz="${isrear*(diff_bar_length/2 + 0.056/2)} 0 0" rpy="0 0 0" />
        </joint>

        <!-- This is the "arms" connected to the steering joint -->
        <joint name="${prefix}_bar_smount_joint" type="fixed">
            <parent link="${prefix}"/>
            <child link="${prefix}_smount"/>
            <origin xyz="${isrear*0.865/8} ${0.04} ${(0.04)*flip_x}" rpy="${pi/2} 0 0" />
        </joint>

        <!-- This is the steering joint -->
        <joint name="${prefix}_smount_fork_joint" type="revolute">
            <parent link="${prefix}_smount"/>
            <child link="${prefix}_wheel_fork"/>
	    <origin xyz="${0} ${0} ${-0.213/2 - 0.03/2}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <!-- FIXME these are the actual limits <limit lower="${-pi/2}" upper="${pi/2}" velocity="5"/> -->
            <limit lower="${-pi}" upper="${pi}" effort="400" velocity="5"/>
        </joint>

        <!-- This is the actual wheel -->
        <joint name="${prefix}_fork_tyre_joint" type="continuous">
            <parent link="${prefix}_wheel_fork"/>
            <child link="${prefix}_tyre"/>
            <origin xyz="0 0 ${-0.05}" rpy="${-pi/2} 0 0" />
            <axis xyz="0 0 1"/>
        </joint>


        <!-- ALL LINKS BELOW THIS LINE -->
	<!-- arm -->
        <link name="${prefix}">
            <visual>
                <geometry>
			<box size="${0.865/2} ${diff_bar_bearing_seat_width} ${diff_bar_bearing_seat_width}"/>
		</geometry>
		<origin xyz="${isrear*-0.865/1.5} 0 0" rpy="0 0 0"/>
                <material name="orange"/>
            </visual>
	    <xacro:inertial_box mass="2" x="${0.865/2}" y="${diff_bar_bearing_seat_width}" z="${diff_bar_bearing_seat_width}">
		    <origin xyz="${isrear*-0.865/1.5} 0 0" rpy="0 0 0"/>
            </xacro:inertial_box>
        </link>

        <!-- Steering motor mount -->
        <link name="${prefix}_smount">
            <visual>
                <geometry>
                    <cylinder radius="${0.0425}" length="0.03"/>
                </geometry>
                <material name="orange"/>
            </visual>
        </link>

        <!-- The actual steering joint -->
        <link name="${prefix}_wheel_fork">
            <visual>
                <geometry>
                    <box size="0.066 0.170 0.213"/>
                </geometry>
                <material name="blue"/>                
            </visual>
            <xacro:inertial_box mass="1" x="0.066" y="0.170" z="0.213">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_box>
        </link>

        <!-- Wheel -->
        <link name="${prefix}_tyre">
            <visual>
                <geometry>
			<cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="2.5" radius="${0.125}" >
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>
    </xacro:macro>
</robot>
