#ifndef SWERVE_DRIVE_CONTROLLER_HPP
#define SWERVE_DRIVE_CONTROLLER_HPP

#include <Eigen/Core>
#include <controller_interface/controller_interface.hpp>
#include <memory>
#include <geometry_msgs/msg/twist_stamped.hpp>
// FIXME: Fix this after realtime_box 3.0.0 is packaged. to use realtime_box.hpp and the new try_get/try_set
// https://github.com/ros-controls/ros2_controllers/commit/f9edc41a451877e292b206069aa2e8bfd25148c0
#include <realtime_tools/realtime_box.h>
#include "visibility_control.h"

// auto-generated by generate_parameter_library package
#include "swerve_drive_controller_parameters.hpp"

namespace swerve_drive_controller
{

class SwerveDriveController : public controller_interface::ControllerInterface {
public:
  SWERVE_DRIVE_CONTROLLER_PUBLIC
  SwerveDriveController() {}

  SWERVE_DRIVE_CONTROLLER_PUBLIC
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  SWERVE_DRIVE_CONTROLLER_PUBLIC
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  SWERVE_DRIVE_CONTROLLER_PUBLIC
  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  SWERVE_DRIVE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_init() override;

  SWERVE_DRIVE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  SWERVE_DRIVE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

  SWERVE_DRIVE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

  SWERVE_DRIVE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_cleanup(
    const rclcpp_lifecycle::State & previous_state) override;

  SWERVE_DRIVE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_error(
    const rclcpp_lifecycle::State & previous_state) override;

  SWERVE_DRIVE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_shutdown(
    const rclcpp_lifecycle::State & previous_state) override;

private:
  // Parameters from ROS for diff_drive_controller
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  rclcpp::Subscription<geometry_msgs::msg::TwistStamped>::SharedPtr velocity_command_subscriber_ = nullptr;

  realtime_tools::RealtimeBox<std::shared_ptr<geometry_msgs::msg::TwistStamped>>
  received_velocity_msg_ptr_{nullptr};

  // Taken from the FRC swerve paper, just uses a 1x3 complex matrix instead of a 2x3 matrix
  // v_m &= \begin{bmatrix} 1 & j & jr_x - r_y  \end{bmatrix} \
  //        \begin{bmatrix} v_x \\ v_y \\ \omega \end{bmatrix}
  Eigen::MatrixX3cd kinematics_;

};
}
#endif
