#!/bin/bash

CAMERA_NUMBER=${1:-"polef"} # figure out what your options are here mate
DEST_ADDR=${2:-localhost}

gst-launch-1.0 -ev v4l2src device=/dev/video-"$CAMERA_NUMBER" ! \
	capsfilter caps=video/x-raw,width=800,height=600,pixelformat=MJPG,framerate=30/1 ! \
	video/x-raw, width=800, height=600, pixelformat=MJPG, framerate=30/1 ! \
	videoconvert $([[ "$CAMERA_NUMBER" != "paver" ]] && echo -n "! rotate angle=3.14") ! videoconvert ! openh264enc ! \
	whipclientsink signaller::whip-endpoint=http://"$DEST_ADDR":8889/webcam-"$CAMERA_NUMBER"/whip
