#!/bin/bash

POSITION=${1:-0.0}
# FL,FR,BL,BR -> 3000,3010,3020,3030
TARGET=${2:-3000}

echo $POSITION
echo $TARGET

yakut -i "CAN(can.media.socketcan.SocketCANMedia('can-all', 64),42)" \
      pub -N 2 ${TARGET}:reg.udral.physics.dynamics.rotation.Planar.0.1\
      "{kinematics: {angular_position: $POSITION }}"

